server:
  port: 8888

spring:
  mvc:
    view:
      prefix: classpath:/templates/
      suffix: .html

  datasource:
    url: jdbc:mysql://120.78.11.128/user?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: Zhangjian0906
    driver-class-name: com.mysql.cj.jdbc.Driver

  #thymeleaf配置
  thymeleaf:
    #缓冲的配置
    cache: false
    check-template: true
    check-template-location: true
    #开启MVC thymeleaf 视图解析
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.mybatis.logging.stdout.StdOutImpl
